publish_url: https://localhost:3000

dfe_signin:
  base_url: https://localhost:3000
teacher_training_api:
  base_url: http://localhost:3001
new_publish:
  base_url: http://localhost:3001/publish
search_ui:
  base_url: https://localhost:5000
environment:
  label: "Test"
  selector_name: "test"
features:
  # Rollover is only enabled for a limited time each year so this explicitly
  # sets it to false. If tests need to test when rollover is enabled then they
  # should set the rollover setting in that test to true
  rollover:
    can_edit_current_and_next_cycles: false
    show_next_cycle_allocation_recruitment_page: false
